/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vivalnk_sdk_demo_core_WfdbUtils */

#ifndef _Included_com_vivalnk_sdk_demo_core_WfdbUtils
#define _Included_com_vivalnk_sdk_demo_core_WfdbUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    initFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_initFile
  (JNIEnv *env, jclass clz, jstring data, jstring hea);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    initSignalInfo
 * Signature: (IILjava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_initSignalInfo
  (JNIEnv *env, jclass clz, jint frequency, jint format, jstring descJStr, jstring unitsJStr, jint gain, jint adcres, jint adczero);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_open
  (JNIEnv *env, jclass clz);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    setBaseTime
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_setBaseTime
  (JNIEnv *env, jclass clz, jstring timeStr);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    doSample
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_doSample
  (JNIEnv *env, jclass clz, jintArray sampleArray);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    newHeader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_newHeader
(JNIEnv *env, jclass clz);

/*
 * Class:     com_vivalnk_sdk_demo_core_WfdbUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vivalnk_sdk_demo_core_WfdbUtils_close
  (JNIEnv *env, jclass clz);

#ifdef __cplusplus
}
#endif
#endif
